//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecretGardenServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public int playerID { get; set; }
        public string playerName { get; set; }
        public string playerPwd { get; set; }
        public string playerAva { get; set; }
        public string playerSign { get; set; }
    }
}
